module LicenseCache

// This is a lookup against a number of standard projects and their license type.
// The NuGet versions here use the legacy license format, so the URL is the only
// thing that will tell you what the license is. This cache means we don't have
// to query the URL each run.
let knownLicenseCache =
    Map.ofList [ ("fsharp.core",
                  Map.ofList [ ("4.5.2", "MIT")
                               ("4.5.1", "MIT") ])
                 ("microsoft.csharp", Map.ofList [ ("4.0.1", "DotNet Library License") ])
                 ("microsoft.netcore.app", Map.ofList [ ("2.2.0", "MIT") ])
                 ("microsoft.netcore.dotnetapphost", Map.ofList [ ("2.2.0", "MIT") ])
                 ("microsoft.netcore.dotnethostpolicy", Map.ofList [ ("2.2.0", "MIT") ])
                 ("microsoft.netcore.dotnethostresolver", Map.ofList [ ("2.2.0", "MIT") ])
                 ("microsoft.netcore.platforms", Map.ofList [ ("2.2.0", "MIT") ])
                 ("microsoft.netcore.targets", Map.ofList [ ("2.0.0", "MIT") ])
                 ("microsoft.win32.primitives", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("microsoft.win32.registry", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("netstandard.library", Map.ofList [ ("2.0.3", "MIT") ])
                 ("newtonsoft.json", Map.ofList [ ("9.0.1", "MIT") ])
                 ("runtime.native.system", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.collections", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.componentmodel.annotations", Map.ofList [ ("4.4.1", "MIT") ])
                 ("system.diagnostics.debug", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.diagnostics.process", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.diagnostics.tools", Map.ofList [ ("4.0.1", "DotNet Library License") ])
                 ("system.dynamic.runtime", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.globalization", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.io", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.io.filesystem", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.io.filesystem.primitives", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.linq", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.linq.expressions", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.objectmodel", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.emit", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.emit.ilgeneration", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.emit.lightweight", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.extensions", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.primitives", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.reflection.typeextensions", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.resources.resourcemanager", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.runtime", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.runtime.extensions", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.runtime.handles", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.runtime.interopservices", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.runtime.serialization.primitives", Map.ofList [ ("4.1.1", "DotNet Library License") ])
                 ("system.security.cryptography.primitives", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.security.cryptography.protecteddata", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.text.encoding", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.text.encoding.extensions", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.text.regularexpressions", Map.ofList [ ("4.1.0", "DotNet Library License") ])
                 ("system.threading", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.threading.tasks", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.threading.tasks.extensions", Map.ofList [ ("4.0.0", "DotNet Library License") ])
                 ("system.threading.thread", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.threading.threadpool", Map.ofList [ ("4.3.0", "DotNet Library License") ])
                 ("system.xml.readerwriter", Map.ofList [ ("4.0.11", "DotNet Library License") ])
                 ("system.xml.xdocument", Map.ofList [ ("4.0.11", "DotNet Library License") ]) ]
