name: CI build

env:
  OUTPUT_PATH: ${{ github.workspace }}/.nupkg
  DOTNET_VERSION: |
    8.0.x
    6.0.x
    9.0.x
  GITHUB_SOURCE: "https://nuget.pkg.github.com/aaronpowell/index.json"
  CONFIGURATION: "Debug"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Generate packages
        run: dotnet fake run ./build.fsx --target CI

      - name: Demonstrate against self
        run: dotnet run --framework net9.0
        working-directory: ./src/DotNetDelice

      - run: ls -la ${{ env.OUTPUT_PATH }}

      - name: Publish release packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ${{ env.OUTPUT_PATH }}

  publish-github:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: GitHub Packages

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: ${{ env.OUTPUT_PATH }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet nuget push --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.GITHUB_SOURCE }} "*.nupkg"
        working-directory: ${{ env.OUTPUT_PATH }}